# GitHub Sponsors and funding links for UTILHELP

# GitHub Sponsors (if you enable it later)
# github: [al1ster13]

# Other popular platforms (uncomment and add your usernames if you use them)
# patreon: your_patreon_username
# ko_fi: your_kofi_username
# liberapay: your_liberapay_username

# Custom funding links
custom: 
  - 'https://www.donationalerts.com/r/al1ster13'
  # You can add more custom links here:
  # - 'https://your-other-donation-platform.com/username'
